import { SelectOption } from '@interfaces';

export const SEGMENT_END_OPTIONS: SelectOption[] = [
  { value: 0, viewValue: 'ECI Position X (meters)' },
  { value: 1, viewValue: 'ECI Position Y (meters)' },
  { value: 2, viewValue: 'ECI Position Z (meters)' },
  { value: 3, viewValue: 'ECI Velocity X (meters/second)' },
  { value: 4, viewValue: 'ECI Velocity Y (meters/second)' },
  { value: 5, viewValue: 'ECI Velocity Z (meters/second)' },
  { value: 6, viewValue: 'ECI Acceleration X (meters/second2)' },
  { value: 7, viewValue: 'ECI Acceleration Y (meters/second2)' },
  { value: 8, viewValue: 'ECI Acceleration Z (meters/second2)' },

  { value: 9, viewValue: 'ECI Euler Angle Roll (degrees)' },
  { value: 10, viewValue: 'ECI Euler Angle Pitch (degrees)' },
  { value: 11, viewValue: 'ECI Euler Angle Yaw (degrees)' },

  { value: 12, viewValue: 'ECI Body Rate Roll (degrees/second)' },
  { value: 13, viewValue: 'ECI Body Rate Pitch (degrees/second)' },
  { value: 14, viewValue: 'ECI Body Rate Yaw (degrees/second)' },

  { value: 15, viewValue: 'ECI Euler Angle Rate Roll (degrees/second)' },
  { value: 16, viewValue: 'ECI Euler Angle Rate Pitch (degrees/second)' },
  { value: 17, viewValue: 'ECI Euler Angle Rate Yaw (degrees/second)' },

  { value: 18, viewValue: 'ECI Angular Acceleration Roll (degrees/second2)' },
  { value: 19, viewValue: 'ECI Angular Acceleration Pitch (degrees/second2)' },
  { value: 20, viewValue: 'ECI Angular Acceleration Yaw (degrees/second2)' },

  { value: 21, viewValue: 'ECEF Position X (meters)' },
  { value: 22, viewValue: 'ECEF Position Y (meters)' },
  { value: 23, viewValue: 'ECEF Position Z (meters)' },
  { value: 24, viewValue: 'ECEF Velocity X (meters/second)' },
  { value: 25, viewValue: 'ECEF Velocity Y (meters/second)' },
  { value: 26, viewValue: 'ECEF Velocity Z (meters/second)' },
  { value: 27, viewValue: 'ECEF Acceleration X (meters/second2)' },
  { value: 28, viewValue: 'ECEF Acceleration Y (meters/second2)' },
  { value: 29, viewValue: 'ECEF Acceleration Z (meters/second2)' },

  { value: 30, viewValue: 'ECEF Euler Angle Roll (degrees)' },
  { value: 31, viewValue: 'ECEF Euler Angle Pitch (degrees)' },
  { value: 32, viewValue: 'ECEF Euler Angle Yaw (degrees)' },

  { value: 33, viewValue: 'ECEF Body Rate Roll (degrees/second)' },
  { value: 34, viewValue: 'ECEF Body Rate Pitch (degrees/second)' },
  { value: 35, viewValue: 'ECEF Body Rate Yaw (degrees/second)' },

  { value: 36, viewValue: 'ECEF Euler Angle Rate Roll (degrees/second)' },
  { value: 37, viewValue: 'ECEF Euler Angle Rate Pitch (degrees/second)' },
  { value: 38, viewValue: 'ECEF Euler Angle Rate Yaw (degrees/second)' },

  { value: 39, viewValue: 'ECEF Angular Acceleration Roll (degrees/second2)' },
  { value: 40, viewValue: 'ECEF Angular Acceleration Pitch (degrees/second2)' },
  { value: 41, viewValue: 'ECEF Angular Acceleration Yaw (degrees/second2)' },

  { value: 42, viewValue: 'Quaternion [body-from-ecef] X' },
  { value: 43, viewValue: 'Quaternion [body-from-ecef] Y' },
  { value: 44, viewValue: 'Quaternion [body-from-ecef] Z' },
  { value: 45, viewValue: 'Quaternion [body-from-ecef] Angle' },
  { value: 46, viewValue: 'NED Velocity North (meters/second)' },
  { value: 47, viewValue: 'NED Velocity East (meters/second)' },
  { value: 48, viewValue: 'NED Velocity Down (meters/second)' },

  { value: 49, viewValue: 'NED Euler Angle Roll (degrees)' },
  { value: 50, viewValue: 'NED Euler Angle Pitch (degrees)' },
  { value: 51, viewValue: 'NED Euler Angle Yaw (degrees)' },

  { value: 52, viewValue: 'NED Angular Velocity X (degrees/second)' },
  { value: 53, viewValue: 'NED Angular Velocity Y (degrees/second)' },
  { value: 54, viewValue: 'NED Angular Velocity Z (degrees/second)' },

  { value: 55, viewValue: 'Body Velocity X (meters/second)' },
  { value: 56, viewValue: 'Body Velocity Y (meters/second)' },
  { value: 57, viewValue: 'Body Velocity Z (meters/second)' },

  { value: 58, viewValue: 'Geodetic Latitude (degrees)' },
  { value: 59, viewValue: 'Longitude (degrees)' },
  { value: 60, viewValue: 'Geodetic Altitude (meters)' },

  { value: 61, viewValue: 'Ground Range (meters)' },

  { value: 62, viewValue: 'Earth Relative Magnitude of Velocity (meters/second)' },
  { value: 63, viewValue: 'Wind Relative Horizontal Flight Path Angle (degrees)' },
  { value: 64, viewValue: 'Wind Relative Vertical Flight Path Angle (degrees)' },
  { value: 65, viewValue: 'Aerodynamic Angle Alpha (degrees)' },
  { value: 66, viewValue: 'Aerodynamic Angle Total Alpha (degrees)' },
  { value: 67, viewValue: 'Aerodynamic Angle Beta (degrees)' },
  { value: 68, viewValue: 'Aerodynamic Angle Phi (degrees)' },

  { value: 69, viewValue: 'Reference Area (meters2)' },
  { value: 70, viewValue: 'Reference Length (meters)' },
  { value: 71, viewValue: 'moment_reference_location_X (meters)' },
  { value: 72, viewValue: 'moment_reference_location_Y (meters)' },
  { value: 73, viewValue: 'moment_reference_location_Z (meters)' },
  { value: 74, viewValue: 'Cx' },
  { value: 75, viewValue: 'Cy' },
  { value: 76, viewValue: 'Cz' },
  { value: 77, viewValue: 'Cl' },
  { value: 78, viewValue: 'Cm' },
  { value: 79, viewValue: 'Cn' },
  { value: 80, viewValue: 'Clp (1/radians)' },
  { value: 81, viewValue: 'Cmq (1/radians)' },
  { value: 82, viewValue: 'Cnr (1/radians)' },

  { value: 83, viewValue: 'Mass (kg)' },
  { value: 84, viewValue: 'Center of Gravity X (meters)' },
  { value: 85, viewValue: 'Center of Gravity Y (meters)' },
  { value: 86, viewValue: 'Center of Gravity Z (meters)' },
  { value: 87, viewValue: 'Moment of Inertia Ixx (kg-m2)' },
  { value: 88, viewValue: 'Moment of Inertia Ixy (kg-m2)' },
  { value: 89, viewValue: 'Moment of Inertia Ixz (kg-m2)' },
  { value: 90, viewValue: 'Moment of Inertia Iyx (kg-m2)' },
  { value: 91, viewValue: 'Moment of Inertia Iyy (kg-m2)' },
  { value: 92, viewValue: 'Moment of Inertia Iyz (kg-m2)' },
  { value: 93, viewValue: 'Moment of Inertia Izx (kg-m2)' },
  { value: 94, viewValue: 'Moment of Inertia Izy (kg-m2)' },
  { value: 95, viewValue: 'Moment of Inertia Izz (kg-m2)' },

  { value: 96, viewValue: 'Body Force X (newtons)' },
  { value: 97, viewValue: 'Body Force Y (newtons)' },
  { value: 98, viewValue: 'Body Force Z (newtons)' },
  { value: 99, viewValue: 'Body Moment X (newton-meters)' },
  { value: 100, viewValue: 'Body Moment Y (newton-meters)' },
  { value: 101, viewValue: 'Body Moment Z (newton-meters)' },
  { value: 102, viewValue: 'Propulsion Body Force X (newtons)' },
  { value: 103, viewValue: 'Propulsion Body Force Y (newtons)' },
  { value: 104, viewValue: 'Propulsion Body Force Z (newtons)' },
  { value: 105, viewValue: 'Propulsion Body Moment X (newton-meters)' },
  { value: 106, viewValue: 'Propulsion Body Moment Y (newton-meters)' },
  { value: 107, viewValue: 'Propulsion Body Moment Z (newton-meters)' },

  { value: 108, viewValue: 'Dynamic Pressure (newtons/meter2)' },
  { value: 109, viewValue: 'Mach' },
  { value: 110, viewValue: 'Atmospheric Density (kg/meter3)' },
  { value: 111, viewValue: 'Atmospheric Pressure (newtons/meter2)' },
  { value: 112, viewValue: 'Atmospheric Speed of Sound (meters/second)' },

  { value: 113, viewValue: 'ECI Gravitational Acceleration X (meters/second2)' },
  { value: 114, viewValue: 'ECI Gravitational Acceleration Y (meters/second2)' },
  { value: 115, viewValue: 'ECI Gravitational Acceleration Z (meters/second2)' },

  { value: 116, viewValue: 'Body Specific Force X (meters/second2)' },
  { value: 117, viewValue: 'Body Specific Force Y (meters/second2)' },
  { value: 118, viewValue: 'Body Specific Force Z (meters/second2)' },

  { value: 120, viewValue: 'Simulation Time (seconds)' },
  { value: 121, viewValue: 'Segment Time (seconds)' },
  { value: 122, viewValue: 'Propulsion Time (seconds)' },
  { value: 123, viewValue: 'User Time (seconds)' },
];
