name: Build
on: 
  push:
    branches:
      - master
      
jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run make
    - name: upload linux distributable
      uses: actions/upload-artifact@v1
      with:
        name: linux
        path: out/linux
      

  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run make
    - name: upload windows distributable
      uses: actions/upload-artifact@v1
      with:
        name: windows
        path: out/windows